### ISSUE TITLE
安装过程中的很多问题

### ISSUE THREAD

**Issue by Miloas** [quark-zju/ljudge#1]
我按照您的README一步一步安装，(ubuntu 14.04 64bit)

``` shell
wget https://github.com/quark-zju/lrun/releases/download/v1.1.3/lrun_1.1.3_amd64.deb
```

居然找不到,然后我发现您的lrun已经更新到1.1.4了，但是这边还没有改，于是我把上面的代码改成1.1.4成功安装了lrun。
但是,装完lrun我发现，/usr/bin/lrun和/usr/bin/lrun-mirrorfs不是可执行文件... 然后我就把这两个chmod成777，执行ljudge --check，提示

```
 lrun doesn't work. Please make sure other issues are resolved
    and try `lrun --debug echo foo` to get some help.
```

然后我执行lrun --debug echo foo，得到

```
FATAL: lrun: root required. (current euid = 1000, uid = 1000) (No such file or directory)
```

我就不知道该咋弄了。。

另外此时的lrun也只能通过sudo lrun 指定uid和gid工作，直接执行lrun的话就会报错

```
FATAL: lrun: root required. (current euid = 1000, uid = 1000) (No such file or directory)
```

**Comment by Miloas** [comment]
难道是我安装lrun的姿势不对，但是我的确是按照README安装的，一步也没少。。

**Comment by Miloas** [comment]
最终看了出问题的代码解决了，设置了lrun的euid然后就可以了

**Comment by quark-zju** [comment]
猜测是安装完 lrun 后没有把当前用户加入 lrun 用户组，加入用户组后需要重新登录生效。安全起见，最好禁止不信任的用户运行 lrun。

**Comment by Miloas** [comment]
可以确定把当前用户加入了lrun的用户组..  但是没有注销重新登陆，orz   非常感谢您的回复

**Comment by Miloas** [comment]
今天重开了一个ubuntu，又装了一次，的确是因为我没有log out的原因，log out后一切正常

**Comment by SilenceHS** [comment]
感谢! 我也遇到相同问题, 我的确是加了lrun组的, 还是不行, 看到你说的euid, 加了后果然ljudge test通过了, centos
