### ISSUE TITLE
docker中INTERNAL_ERROR

### ISSUE THREAD

**Issue by YuTaoFighting** [quark-zju/ljudge#10]
```
a.c: ERROR 
{
    "compilation" : {
        "error" : "lrun exited with non-zero (14)ERROR: exec 'gcc' failed (No such file or directory)",
        "log":"",
        "success":false
    }
}
a.txt: ERROR 
{
    "compilation" : {
        "log":"",
        "success" : true
    },
    "testcases" : [
        {
            "error" : "lrun exited with non-zero (14)",
            "result":"INTERNAL_ERROR",
            "stderr":"ERROR: exec 'cat' failed (Permission denied)",
            "stdout":""
        }
    ]
}
```
不知为什么gcc执行没问题，报gcc不存在的错误，cat报权限问题

**Comment by quark-zju** [comment]
您好，诊断这个问题需要更详细的信息。建议使用 ljudge 的 `--debug` 选项来获得具体的 lrun 命令，然后使用 `strace -f lrun ...` 来看看具体出错信息，或者使用 `lrun ... /bin/bash` （将 gcc 换成 bash）来手动检查一下环境设置有没有问题。依据已有信息，可能的原因有：

- PATH 设置不当
- gcc 的其他依赖并未包含在文件系统白名单内
- 其他 Linux 安全组件（如 SE Linux）做了一些额外的限制

lrun 使用的容器技术和 docker 相同，条件允许的话可以跳过 docker 直接部署 lrun。我们最初使用 lrun 的场景是没有使用 docker 的。安全性上，在 docker 内套用 lrun 和直接使用 lrun 应该是接近的。

**Comment by YuTaoFighting** [comment]
非常感谢，直接部署没问题了。
