### ISSUE TITLE
想请问一下，能否作为毕业设计的引用

### ISSUE THREAD

**Issue by SilenceHS** [quark-zju/ljudge#11]
你好，我的毕设题目是制作一个ACM网站，我自己写的判题核心只能判C语言，然后想问一下可否使用您的判题核心，如果可以，那论文注明判题核心来源的话，可以留这个github链接或者您的姓名或者需要我注明其他信息吗，谢谢！

**Comment by quark-zju** [comment]
您好，在 https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository 可以找到一些引用 GitHub 的例子。好像姓名，年份，概述和 GitHub 链接就可以了。我也根据 https://guides.github.com/activities/citable-code/ 说明在 Zendo 网站上注册了这个项目的最新版本，见 https://zenodo.org/record/3724996 。如果需要使用 DOI 引用之前的版本我也可以帮忙上传。

**Comment by SilenceHS** [comment]
明白了，谢谢！感谢回复！那这个issue就先关了哦
