### ISSUE TITLE
运行报错,需要root权限

### ISSUE THREAD

**Issue by eventlOwOp** [quark-zju/ljudge#12]
当我用root运行的时候,提示以下:
`Running ljudge --check using root is not supported.
Please switch to a non-root user and try again.`
我用非root运行的时候(已经gpasswd -a $USER lrun)
提示lrun不工作,按照提示运行lrun --debug echo foo
提示:
`[   0.000][  2263] FATAL: lrun: root required. (current euid = 1000, uid = 1000) (No such file or directory)
  at lrun.cc:become_root:63`
所以用啥用户都不行...
?????????????????????????
请问如何解决
谢谢

**Comment by eventlOwOp** [comment]
我的lrun和ljudge是用root用户编译安装的master分支

**Comment by quark-zju** [comment]
可能的原因：

在 `gpasswd -a $USER lrun` 之后需要登出 `$USER` 才能生效。
检查 lrun 文件的权限，贴一下 `ls -l $(which lrun)` 的输出？

**Comment by eventlOwOp** [comment]
登出了还是一样
ls -l $(which lrun)输出-rwxrwxrwx 1 root lrun 1684008 Mar 25 22:45 /usr/local/bin/lrun
/usr/local目录设置成了777的权限

**Comment by eventlOwOp** [comment]
您好,谢谢,问题已经解决了
我查阅了相关资料,需要把lrun的euid设置成0,需要使用chmod a+s /usr/local/bin/lrun
已经可以使用了
