### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by eventlOwOp** [quark-zju/ljudge#13]
您好,我想问一下这个问题如何解决,谢谢,请问一下这个临时文件的生成位置在哪里
`{
  "compilation": {
    "log": "Cannot create temporary file in .\/: Permission denied\n\nCompiler was killed by signal 6\n\n",
    "success": false
  }
`}

**Comment by eventlOwOp** [comment]
当我换用低版本的lrun和ljudge时就可以成功执行

**Comment by quark-zju** [comment]
建议使用 `--debug` 和 `strace -f` 来诊断这一类问题。比较可能的原因是 ljudge 的默认配置和你当前的编译器环境不兼容。你也可以 git bisect ljudge 来定位问题是在哪里。

**Comment by AmazingDaFaFa** [comment]
> 您好,我想问一下这个问题如何解决,谢谢,请问一下这个临时文件的生成位置在哪里
> `{ "compilation": { "log": "Cannot create temporary file in .\/: Permission denied\n\nCompiler was killed by signal 6\n\n", "success": false } `}

请问你有找到除了重装低版本以外的解决方案吗？我也遇到了同样的问题orz

**Comment by AmazingDaFaFa** [comment]
您好，我已收到您的邮件，方便时会给您回复！
