### ISSUE TITLE
--output-sha1

### ISSUE THREAD

**Issue by YuTaoFighting** [quark-zju/ljudge#15]
--output-sha1 ac-chomp-sha1,pe-sha1
请问一下，ac-chomp-sha1,pe-sha1分别代表哪个文件的sha1sum值

**Comment by quark-zju** [comment]
AC 代表正确参考输出的 SHA1，chomp 表示去除最后的一个换行符。PE 表示 "Presentation Error" 格式错误时使用的 SHA1，应该是去除所有空白符号之后的 SHA1。
