### ISSUE TITLE
lrun exited with non-zero (1)

### ISSUE THREAD

**Issue by dinggz1982** [quark-zju/ljudge#17]
正确安装了，但测评报错lrun exited with non-zero ：
{
  "compilation": {
    "log": "",
    "success": true
  },
  "testcases": [
    {
      "error": "lrun exited with non-zero (1)",
      "result": "INTERNAL_ERROR"
    },
    {
      "error": "lrun exited with non-zero (1)",
      "result": "INTERNAL_ERROR"
    }
  ]
}

**Comment by dinggz1982** [comment]
解决了，安装lrun之前要先安装libseccomp-devel，我的centos系统，故运行：yum install  libseccomp-devel.
安装完后用lrun --version看看，显示：
libseccomp support: yes
debug support: yes
这样再安装ljudge，就可以正常运行了。
如果显示：
libseccomp support: no
debug support: yes
就要重新安装lrun，我是重置了系统。

**Comment by quark-zju** [comment]
也可以通过 `ljudge --check` 来排查问题。
