### ISSUE TITLE
在Docker中部署lrun，程序在子系统下创建lrun*文件失败

### ISSUE THREAD

**Issue by Miloas** [quark-zju/ljudge#2]
今天在docker里装了纯洁ubuntu14.04，然后打算部署lrun，完成后执行：

``` shell
$ lrun --debug echo foo
```

发现子系统下不能创建lrun*文件，是`Read-only file system`

是不是docker对镜像中的cgroups使用有啥限制？

不清楚cgroups需要怎样的权限，也有可能是我创建的用户有问题，创建完系统镜像，我`adduser xxx`，然后用root用户设置了xxx的密码，在sudoers文件里写入 `xxx = ALL(ALL) ALL`，用xxx用户安装的lrun，并把xxx加入lrun 用户组.

**Comment by quark-zju** [comment]
参考这里 https://github.com/quark-zju/lrun/issues/20#issuecomment-68146198

需要用特权 Docker 才能运行 lrun，从安全性来说 Docker 在此并不能带来明显好处。

**Comment by Miloas** [comment]
非常感谢，主要是为了部署方便，:)
