### ISSUE TITLE
重新装了环境，如何重新生成mirrors

### ISSUE THREAD

**Issue by zhouyusd** [quark-zju/ljudge#21]
本来没装python2，但是已经生成了mirrorfs， 然后就会报找不到python2的错误，原来的mirror也删不掉，如何重新生成？

**Comment by quark-zju** [comment]
`lrun-mirrorfs` 有一个 `--teardown` 选项，试试看？也可以重启。

**Comment by zhouyusd** [comment]
Thanks!
