### ISSUE TITLE
checker不支持testlib吗?

### ISSUE THREAD

**Issue by zhouyusd** [quark-zju/ljudge#22]
使用quitf后，
```json
{
  "checkerCompilation": {
    "log": "",
    "success": true
  },
  "compilation": {
    "log": "",
    "success": true
  },
  "testcases": [
    {
      "error": "unknown checker exit code 3",
      "memory": 266240,
      "result": "INTERNAL_ERROR",
      "time": 1323280
    }
  ]
}
```

**Comment by quark-zju** [comment]
ljudge 当时主要是兼容 ZOJ 的自定义判题程序的需求，具体而言十分简单，就是看返回值，0 是 AC，1 和 -1 (255) 是 WA，2 是 PE。输入输出文件名是固定的。实际主要使用场景是允许浮点数有一定误差。

我大致看了一下 [testlib](https://github.com/MikeMirzayanov/testlib/blob/master/testlib.h#L219-L255)，它也使用了 0，1，2 作为 AC，WA 和 PE，这部分恰巧是兼容的。剩下的返回值在 ljudge 看来就全是"自定义判题程序发生了内部错误"，只是 ljudge 没有去规范说再到哪里去读取错误信息显示出来，这时候你看到的 `INTERNAL_ERROR` 的判题结果是对的，因为自定义判题程序没有按预期返回一个确定的结果（AC, WA, PE）。

testlib 看起来挺复杂的，还有 Generator 这样生成测试数据的功能，这个 ljudge 目前是不支持的。如果只是使用 testlib Checker 部分的逻辑的话，我觉得不使用 testlib 自行实现也没什么复杂的，五千行的 testlib 可能也没法帮你省下来几行。

**Comment by zhouyusd** [comment]
Thanks！
