### ISSUE TITLE
File format problem.

### ISSUE THREAD

**Issue by WuTianming** [quark-zju/ljudge#3]
输出答案和程序输出进行比对的时候，若输出答案是DOS编码（`\r\n`结尾，Windows标准编码；而Unix格式是`\n`结尾），就会导致`PRESENTATION_ERROR`。猜测是由于逐字节比对造成。

建议解决方案 直接用系统的diff，省掉很多麻烦

**Comment by quark-zju** [comment]
输出答案应该保证不是 Windows 编码。这一点应该由出题人保证，如果有 Web 界面编辑出题数据，可以考虑适当给出警告并提供转换功能，不应该在 ljudge 这一层实现。原因如下：
- 运行 diff 的开销相比目前的比较逻辑来说，明显要大
- 若 diff 程序不存在或不是期望的版本则会有潜在风险

另外，并非所有题目的输出都是文本格式。如果一定有特殊的比较需求，可以使用自定义判题程序来实现。

**Comment by quark-zju** [comment]
出于性能考虑，ljudge 不应该默认使用外部 diff 程序。
